name: claspenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - cython
  - jinja2
  - networkx
  - sympy
  - pip:
      - graphein==1.7.7
      - transformers==4.53.2
      - biopython==1.85
      - bioservices==1.12.1
      - tqdm==4.67.1
      - requests==2.32.4
      - beautifulsoup4==4.13.4
      - line-profiler==4.2.0
      - clip==0.2.0
      - cpdb-protein==0.2.0
      - propcache==0.3.2
      - torch-geometric==2.6.1
